#!/usr/bin/env python3
"""set1: tables and verbatim texts from the staged cell runs (host only, read-only on the runs).
usage: summary.py STAGE  -> writes sections-table.md, texts-en-tr.md, checks-not-passed.txt, native-facts.json"""
import glob
import json
import os
import sys
from pathlib import Path

stage = Path(sys.argv[1])
STANDARD = {"section", "title", "node", "native_evidence", "started_at", "finished_at", "calls", "checks", "natives",
            "notes", "owner_actions", "verdict", "substeps", "error", "owner_waited_for_idle"}
runs = sorted(p for p in stage.glob("set1-*/run-*") if (p / "result.json").exists() or (p / "steps").is_dir())
table, texts, bad, facts = [], {}, [], {}
# the verbatim-text file takes each platform's latest run (an earlier run of the same platform is a harness re-run)
latest = {}
for run in runs:
    latest[run.parent.name] = run
for run in runs:
    name = f"{run.parent.name}/{run.name}"
    result = json.loads((run / "result.json").read_text(encoding="utf-8")) if (run / "result.json").exists() else {}
    steps = {s["name"]: s for s in result.get("steps", [])}
    table.append(f"\n### {name}: overall `{result.get('overall')}`, node {result.get('cell', {}).get('node')}, "
                 f"`native_evidence: {json.dumps(result.get('native_evidence'))}`\n")
    table.append("| Step | Verdict | Started (UTC) | Finished (UTC) |\n| --- | --- | --- | --- |")
    for s in result.get("steps", []):
        table.append(f"| {s['name']} | {s['verdict']} | {s.get('started_at')} | {s.get('finished_at')} |")
    table.append("\n| Section | Verdict | Sub-steps | Checks | Not passed |\n| --- | --- | --- | --- | --- |")
    sections = {}
    for path in sorted(glob.glob(str(run / "steps" / "*" / "section.json"))):
        d = json.loads(Path(path).read_text(encoding="utf-8"))
        sections[d["section"]] = (d, os.path.relpath(path, stage).replace("\\", "/"))
    for key, info in (result.get("sections") or {}).items():
        if key not in sections:
            table.append(f"| {key} | {info.get('verdict')} | - | - | {info.get('reason') or ''} |")
            continue
        d, rel = sections[key]
        subs = ", ".join(f"{k} {v}" for k, v in d.get("substeps", {}).items())
        notp = [c["name"] for c in d["checks"] if c["ok"] is not True]
        table.append(f"| {key} | **{d['verdict']}** | {subs} | {len(d['checks'])} | "
                     f"{'; '.join(n[:110] for n in notp) or '-'}{' ERROR: ' + d['error'][:200] if d.get('error') else ''} |")
        for c in d["checks"]:
            if c["ok"] is not True:
                bad.append(f"{name} {key} {'FAIL' if c['ok'] is False else 'NOT-ESTABLISHED'}: {c['name']}\n    "
                           + json.dumps(c["detail"], ensure_ascii=False)[:2500])
        if d.get("error"):
            bad.append(f"{name} {key} ERROR: {d['error']}")
        for n in d.get("notes", []):
            bad.append(f"{name} {key} note: {n['note']}\n    " + json.dumps(n.get("detail"), ensure_ascii=False)[:1500])
        facts.setdefault(name, {})[key] = {k: v for k, v in d.items() if k not in STANDARD}
        facts[name][key]["owner_actions"] = [a["label"] for a in d.get("owner_actions", [])]
        for call in d["calls"] if latest[run.parent.name] == run else []:
            answer = call.get("answer") or {}
            cat = call.get("catalogue_texts") or {}
            if not answer and not cat:
                continue
            ident = (key, call["status"], answer.get("code"), answer.get("reason"), answer.get("error"),
                     json.dumps(cat, sort_keys=True, ensure_ascii=False))
            entry = texts.setdefault(ident, {"runs": [], "labels": [], "vars": [], "flags": {}})
            if run.parent.name not in entry["runs"]:
                entry["runs"].append(run.parent.name)
            if call["label"] not in entry["labels"]:
                entry["labels"].append(call["label"])
            if answer.get("vars") and answer["vars"] not in entry["vars"]:
                entry["vars"].append(answer["vars"])
            for flag in ("partial_success", "mutation_applied"):
                if answer.get(flag) is not None:
                    entry["flags"][flag] = answer[flag]

(stage / "sections-table.md").write_text("# set1: steps and sections per run (generated by tools/summary.py)\n"
                                         + "\n".join(table) + "\n", encoding="utf-8", newline="\n")
out = ["# set1: the Panel's answers, verbatim (generated by tools/summary.py)\n",
       "For each distinct answer: the HTTP status, `code` and `reason`, the API's own sentence (the API answers in "
       "English only), the values it carried, and the sentences the installed build's EN/TR catalogues hold for the "
       "screen (looked up by key; the driver does not render a screen).\n"]
for ident in sorted(texts, key=lambda i: (i[0], str(i[2]), str(i[3]), i[1])):
    key, status, code, reason, error, cat = ident
    entry = texts[ident]
    out.append(f"\n## {key}: HTTP {status} `{code or '-'}`" + (f" / `{reason}`" if reason else ""))
    out.append(f"- runs: {', '.join(entry['runs'])}; requests: {'; '.join(entry['labels'])}")
    if error:
        out.append(f"- API (EN): \"{error}\"")
    for v in entry["vars"]:
        out.append(f"- vars: `{json.dumps(v, ensure_ascii=False)}`")
    if entry["flags"]:
        out.append(f"- flags: `{json.dumps(entry['flags'])}`")
    for ckey, both in json.loads(cat).items():
        out.append(f"- catalogue `{ckey}`\n  - EN: \"{both.get('en')}\"\n  - TR: \"{both.get('tr')}\"")
(stage / "texts-en-tr.md").write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
(stage / "checks-not-passed.txt").write_text("\n".join(bad) + "\n", encoding="utf-8", newline="\n")
(stage / "native-facts.json").write_text(json.dumps(facts, indent=1, ensure_ascii=False, sort_keys=True) + "\n",
                                         encoding="utf-8", newline="\n")
print("runs", [f"{r.parent.name}/{r.name}" for r in runs], "answers", len(texts), "not-passed lines", len(bad))
