Match User celikpeer
    AuthenticationMethods publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    AuthorizedKeysFile /etc/ssh/authorized_keys/celikpeer
    DisableForwarding yes
    PermitTTY no
    PermitUserRC no
    ForceCommand /opt/celikpanel/libexec/pdns-peer-inspect-forced
