<?php declare(strict_types=1); ?>
<section class="member-terms">
<p><?=t('Geçerli metin: 10 Eylül 2026.','Effective text: 10 September 2026.')?></p>
<h2><?=t('Ürün ve ücretsiz lisans','Product and free license')?></h2>
<p><?=t('CelikPanel, CELIKBROS tarafından sunulan sunucu yönetim yazılımıdır. Şu an bir üyelik hesabından ücretsiz lisans alabilirsiniz. Her lisans bir aktif sunucuda kullanım içindir; oluşturulduğu tarihten itibaren bir takvim yılı geçerlidir. Kendi sitelerinizi barındırabilir veya müşterilerinize ve bayilerinize hosting hizmeti verebilirsiniz.','CelikPanel is server management software provided by CELIKBROS. You can currently obtain free licenses from a member account. Each license covers one active server for one calendar year from creation. You may host your own sites or provide hosting to your customers and resellers.')?></p>
<p><?=t('Bu kullanım izni yazılımın mülkiyetini veya kaynak kodunu yeniden dağıtma hakkını devretmez. Üçüncü taraf bileşenlerin kendi lisansları geçerlidir. CelikPanel şu anda alfa aşamasındadır; ilk denemenizi temiz bir test sunucusunda yapın.','This permission does not transfer ownership of the software or grant source redistribution rights. Third-party components retain their own licenses. CelikPanel is currently in alpha; begin on a clean test server.')?></p>
<h2><?=t('Yenileme ve sunucu değişimi','Renewal and server transfer')?></h2>
<p><?=t('Yenileme şu anda ücretsizdir; son 30 günde veya süre dolduktan sonra hesabınızdan yapılabilir. Ücretli satış eklenirse fiyat ve koşullar satın alma öncesinde gösterilir; otomatik ödeme alınmaz. Lisans, ilk bağlantıda doğrulanan genel IP adresiyle eşleşir. Aynı IP üzerinde yeniden kurulumda aynı anahtar kullanılabilir. IP değişirse hesabınızdan sunucu eşlemesini kaldırıp aynı anahtarla tekrar etkinleştirin. Bu işlemler mevcut lisansın süresini yeniden başlatmaz.','Renewal is currently free and available from your account during the last 30 days or after expiry. If paid sales are introduced, prices and terms will be shown before purchase; no automatic charges are made. The license binds to the public IP verified on first connection. Reinstalling at the same IP can reuse the same key. If the IP changes, release the server binding from your account and activate with the same key. These operations do not restart the license term.')?></p>
<p><?=t('Aktif lisans yoksa veya süresi dolmuşsa tüm kullanıcıların panel ve yönetim API erişimi kapanır. Yönetici lisansı etkinleştirebilir veya yenileyebilir; giriş, çıkış ve kendi hesabını kurtarma işlemleri erişilebilir kalır. Çalışan siteler, e-posta, veritabanları ve mevcut zamanlanmış görevler durdurulmaz. Panel veya API kullanılırken tüm kullanıcılar için ortak lisans sonucu günlük yenilenir. Kullanım yokken otomatik merkezi kontrol yapılmaz. Geçici bağlantı sorunlarında son doğrulanmış sonuç, lisans bitişini aşmamak üzere en fazla 7 gün kullanılabilir. Bu sınırdan sonra doğrulama tamamlanana kadar panel erişimi kapalı kalır.','Without an active license, or after expiry, panel and management API access is locked for all users. The administrator can activate or renew the license; sign-in, sign-out and own-account recovery remain available. Running websites, mail, databases and existing scheduled tasks are not stopped. During panel or API use, one shared license result is refreshed daily for all users. Idle servers do not make automatic central checks. During a connection outage, the last verified result may be used for up to 7 days, never beyond license expiry. After that limit, panel access remains locked until verification succeeds.')?></p>
<h2><?=t('Hesap ve lisans verileri','Account and license data')?></h2>
<p><?=t('CELIKBROS üyelik hizmeti e-posta adresinizi, parolanızın tek yönlü özetini, e-posta doğrulama durumunu, kabul ettiğiniz metnin sürümünü, lisans tarihlerini, anahtar özetlerini ve şifrelenmiş anahtarları, eşleşen genel IP adresini, sunucunun türetilmiş kimliğini ve adını, aktivasyon ve yenileme kayıtlarını saklar. Bu bilgiler hesabı çalıştırmak, lisansları yönetmek ve kötüye kullanımı sınırlamak için kullanılır. IP adresiniz istek sınırlamasında özetlenerek işlenir; web sunucusu erişim günlükleri ayrıca IP adresi içerebilir.','The CELIKBROS membership service stores your email, a one-way password hash, verification status, the accepted text version, license dates, key hashes and encrypted keys, the bound public IP address, a derived server identity and hostname, and activation and renewal records. These support account operation, license management and abuse prevention. Request limits use a hash derived from your IP address; web server access logs may separately contain IP addresses.')?></p>
<p><?=t('Sunucunuzun root parolası, panel yöneticisi parolası, müşteri hesapları, site dosyaları ve e-postalar lisans hizmetine gönderilmez. Giriş oturumu için gerekli bir çerez kullanılır. Doğrulama ve parola yenileme e-postaları mevcut posta hizmeti üzerinden gönderilir; bu üyelik akışı reklam veya analiz çerezi eklemez.','Your server root password, panel administrator password, customer accounts, site files and emails are not sent to the licensing service. An essential session cookie is used for sign-in. Verification and password reset emails use the existing mail service; this membership flow adds no advertising or analytics cookies.')?></p>
<p><?=t('Hesap ve lisans kayıtları hizmeti sağlamak için saklanır. Hesap, veri veya lisansla ilgili talepleriniz için websitesinin Destek bölümündeki iletişim yolunu kullanın.','Account and license records are retained to provide the service. For account, data or license requests, use the contact route in the website’s Support section.')?> <a href="/#destek"><?=t('Destek','Support')?></a></p>
</section>
