"""set8: every step not `passed` and every check not True, of every staged run (read only). usage: notpassed.py EVIDENCE_DIR"""
import glob, json, os, sys
E = sys.argv[1]
total = bad = 0
print("# Steps and checks that did not pass (generated by tools/notpassed.py); `observed` is listed too\n")
for d in sorted(glob.glob(os.path.join(E, "*", "run-*", "driver"))):
    g = os.path.relpath(os.path.dirname(d), E).replace("\\", "/")
    for s in json.load(open(os.path.join(d, "result.json"), encoding="utf-8"))["steps"]:
        if s["verdict"] != "passed":
            print(f"{g}: step {s['name']}: {s['verdict']} {s.get('reason') or ''}")
    for p in sorted(glob.glob(os.path.join(d, "steps", "*", "section.json"))):
        for c in json.load(open(p, encoding="utf-8")).get("checks", []):
            total += 1
            if c["ok"] is not True:
                bad += 1
                print(f"{g}: check {c['ok']}: {c['name']}")
print(f"\nchecks in sections: {total}; not True: {bad}")
