'use strict';
const $=id=>document.getElementById(id);
const copy={en:{title:'Recovery status',intro:'Read the recorded result of this operation. Checking status does not restart recovery.',language:'Language',code:'Temporary access code',open:'View operation',help:'Use the code shown in your SSH terminal. It only opens this temporary status view.',check:'Check status',checking:'Checking…',close:'Lock this view',foot:'This view is independent of Panel and Agent. Close its SSH command with Ctrl+C to end access. Normal panel access and service health are checked separately.',unavailable:'The current result could not be confirmed. The last known result remains below. Check the SSH connection, then check this same operation again.',first:'The result could not be confirmed. Check the SSH connection and this same operation again.',denied:'The access code was not accepted. Enter the code from the running SSH command.',ended:'This temporary view has expired. Open a new view from your SSH terminal.',locked:'View locked. The recovery operation continues independently.',expires:'Access expires: ',phases:{accepted:'Update accepted',running:'Update in progress',recovering:'Recovery in progress',failed:'Update reported a failure',recovery_required:'Recovery needs attention',recovered:'Restoration verified',succeeded:'Update completion verified'},paused:'Automatic recovery paused',waiting:'Waiting for the operating system',empty:'Result not yet confirmed',request:'Operation',recorded:'Recorded at',failure:'Previous failure',reasons:{update_failed:'The update reported a failure.',recovery_failed:'Recovery reported a failure.',recovery_incomplete:'Recovery has not been verified.',none:'No earlier failure is recorded.'}},
tr:{title:'Kurtarma durumu',intro:'Bu işlemin kaydedilen sonucunu okuyun. Durum sorgusu kurtarmayı yeniden başlatmaz.',language:'Dil',code:'Geçici erişim kodu',open:'İşlemi görüntüle',help:'SSH terminalinde gösterilen kodu kullanın. Yalnız bu geçici durum ekranını açar.',check:'Durumu kontrol et',checking:'Kontrol ediliyor…',close:'Bu ekranı kilitle',foot:'Bu ekran Panel ve Agent’tan bağımsızdır. Erişimi kapatmak için SSH komutunu Ctrl+C ile durdurun. Normal panel erişimi ve hizmet sağlığı ayrıca kontrol edilir.',unavailable:'Güncel sonuç doğrulanamadı. Son bilinen sonuç aşağıda korunuyor. SSH bağlantısını kontrol edip aynı işlemi yeniden sorgulayın.',first:'Sonuç doğrulanamadı. SSH bağlantısını kontrol edip aynı işlemi yeniden sorgulayın.',denied:'Erişim kodu kabul edilmedi. Çalışan SSH komutunun gösterdiği kodu girin.',ended:'Bu geçici ekranın süresi doldu. SSH terminalinizden yeni bir ekran açın.',locked:'Ekran kilitlendi. Kurtarma işlemi bağımsız olarak devam eder.',expires:'Erişimin bitişi: ',phases:{accepted:'Güncelleme kabul edildi',running:'Güncelleme sürüyor',recovering:'Kurtarma sürüyor',failed:'Güncelleme hata bildirdi',recovery_required:'Kurtarma için işlem gerekiyor',recovered:'Geri yükleme doğrulandı',succeeded:'Güncellemenin tamamlanması doğrulandı'},paused:'Otomatik kurtarma durdu',waiting:'İşletim sistemi bekleniyor',empty:'Sonuç henüz doğrulanmadı',request:'İşlem',recorded:'Kayıt zamanı',failure:'Önceki hata',reasons:{update_failed:'Güncelleme hata bildirdi.',recovery_failed:'Kurtarma hata bildirdi.',recovery_incomplete:'Kurtarma henüz doğrulanmadı.',none:'Önceki hata kaydı yok.'}}};
let lang=document.documentElement.lang==='tr'?'tr':'en',token='',last=null,busy=false,notice='',pending=null;
$('language').value=lang;
function render(){const t=copy[lang];document.documentElement.lang=lang;document.title='CelikPanel · '+t.title;
for(const [id,key] of Object.entries({title:'title',intro:'intro','language-label':'language','code-label':'code',open:'open','code-help':'help',close:'close',foot:'foot','request-label':'request','recorded-label':'recorded','failure-label':'failure'}))$(id).textContent=t[key];
$('check').textContent=busy?t.checking:t.check;$('check').disabled=busy;$('open').disabled=busy;
$('access').hidden=!!token;$('result').hidden=!token;$('notice').textContent=t[notice]||(busy?t.checking:'');$('state-title').textContent=t.empty;$('details').textContent='';$('expires').textContent='';for(const id of ['request','recorded','failure'])$(id).textContent='';
if(last){const s=last.status;$('state-title').textContent=s.automatic_recovery?t.paused:s.waiting_for?t.waiting:t.phases[s.phase];$('details').textContent=last[lang].split('\n')[0];$('request').textContent=s.request_id;$('recorded').textContent=new Date(s.observed_at).toLocaleString(lang==='tr'?'tr-TR':'en-US');$('failure').textContent=t.reasons[s.previous_failure||'none']||t.reasons.recovery_incomplete;$('expires').textContent=t.expires+new Date(last.expires_at).toLocaleString(lang==='tr'?'tr-TR':'en-US');}}
function lock(message){pending?.abort();pending=null;token='';last=null;busy=false;notice=message;$('code').value='';render();$('code').focus();}
async function check(){if(!token||busy)return;busy=true;const request=new AbortController();pending=request;const timer=setTimeout(()=>request.abort(),8000);render();
try{const res=await fetch('/status',{headers:{Authorization:'Bearer '+token},cache:'no-store',credentials:'omit',signal:request.signal});
if(pending!==request)return;if(res.status===401){lock('denied');return;}if(res.status===410){lock('ended');return;}if(!res.ok)throw new Error('unavailable');
const value=await res.json(),s=value.status;if(pending!==request)return;
if(s?.schema!=='celikpanel-recovery-status/v1'||!(/^[a-f0-9]{32}$/).test(s.request_id)||s.observation!=='known'||!copy.en.phases[s.phase]||typeof value.en!=='string'||typeof value.tr!=='string'||!Number.isFinite(Date.parse(s.observed_at))||!Number.isFinite(Date.parse(value.expires_at)))throw new Error('unavailable');
if(last&&last.status.request_id!==s.request_id)throw new Error('unavailable');
const terminal=last&&last.status.terminal_proof!=='none';
if(!last||(!terminal&&s.observed_at>=last.status.observed_at)){last=value;}notice='';
}catch{if(pending===request)notice=last?'unavailable':'first';}
finally{clearTimeout(timer);if(pending===request){pending=null;busy=false;render();}}}
$('access').addEventListener('submit',event=>{event.preventDefault();const value=$('code').value.trim();$('code').value='';if(!(/^[a-f0-9]{64}$/).test(value)){notice='denied';render();return;}token=value;notice='';void check();});
$('check').addEventListener('click',()=>void check());$('close').addEventListener('click',()=>lock('locked'));
$('language').addEventListener('change',()=>{lang=$('language').value==='tr'?'tr':'en';render();});
setInterval(()=>{if(document.visibilityState==='visible')void check();},5000);render();
