// Kept independent of the normal application's translation loader.
export const copy = {
    en: {
        title: 'The panel connection is unavailable',
        help: 'This recovery page is saved in your browser. It cannot confirm the server’s current state. A lost connection does not prove that your update failed or your license expired.',
        next: 'Check your connection. This page checks again every 15 seconds while visible. When the panel responds, open it to continue tracking the same operation.',
        check: 'Check connection', checking: 'Checking connection…',
        waiting: 'No current panel response. This page has not started another operation.',
        reachable: 'The panel is responding. Open it to sign in or verify the existing operation.',
        open: 'Open panel', reference: 'Saved operation reference',
        referenceHelp: 'This ID is a browser hint, not a verified result or permission to retry.',
        owner: 'If the connection does not return',
        ownerHelp: 'The server administrator can inspect recovery through an existing SSH connection. These commands only read status; they do not restart an update.',
        noReference: 'No operation reference is saved in this browser. Ask the server administrator to inspect the recovery journal.',
        journal: 'Read the recovery journal', status: 'Read this operation’s status',
    },
    tr: {
        title: 'Panel bağlantısına ulaşılamıyor',
        help: 'Bu kurtarma sayfası tarayıcınızda kayıtlıdır. Sunucunun güncel durumunu doğrulayamaz. Bağlantının kesilmesi, güncellemenin başarısız olduğunu veya lisansın süresinin dolduğunu göstermez.',
        next: 'Bağlantınızı kontrol edin. Bu sayfa açıkken 15 saniyede bir yeniden kontrol eder. Panel yanıt verdiğinde aynı işlemi izlemek için paneli açın.',
        check: 'Bağlantıyı kontrol et', checking: 'Bağlantı kontrol ediliyor…',
        waiting: 'Panelden güncel yanıt alınamadı. Bu sayfa yeni bir işlem başlatmadı.',
        reachable: 'Panel yanıt veriyor. Giriş yapmak veya mevcut işlemi doğrulamak için paneli açın.',
        open: 'Paneli aç', reference: 'Kayıtlı işlem kimliği',
        referenceHelp: 'Bu kimlik tarayıcıda kayıtlı bir ipucudur; doğrulanmış sonuç veya yeniden deneme yetkisi değildir.',
        owner: 'Bağlantı geri gelmezse',
        ownerHelp: 'Sunucu yöneticisi mevcut SSH bağlantısından kurtarma durumuna bakabilir. Bu komutlar yalnızca durumu okur; güncellemeyi yeniden başlatmaz.',
        noReference: 'Bu tarayıcıda kayıtlı işlem kimliği yok. Sunucu yöneticisinden kurtarma günlüğünü incelemesini isteyin.',
        journal: 'Kurtarma günlüğünü oku', status: 'Bu işlemin durumunu oku',
    },
};
