"""set3: README.md from README.template.md and the generated tables.

usage: mkreadme.py EVIDENCE_DIR VALUES_JSON TEMPLATE...
The templates are concatenated; VALUES_JSON holds the hand-written placeholders. Generated placeholders:
{{BUILD_TABLE}} {{PART1_TABLE}} {{PART1_REGRESSION}} {{PART2_TABLE}} {{PART2_FACTS_GOOD}} {{PART2_FACTS_BACK}} {{CELLS_TABLE}}
{{CDRIVE}}
"""
import glob
import json
import os
import re
import sys

E, values_file, templates = sys.argv[1].rstrip("/\\"), sys.argv[2], sys.argv[3:]


def read(name):
    try:
        return open(os.path.join(E, name), encoding="utf-8-sig").read()
    except OSError:
        return ""


def build_table():
    rows = ["| Build (folder under `build/`) | Role | Label / seq | Commit | Tree | Archive SHA-256 |", "| --- | --- | --- | --- | --- | --- |"]
    for name in ("cur", "a81-first", "a81"):
        try:
            doc = json.load(open(os.path.join(E, "build", name, "upd1-artifacts.json"), encoding="utf-8"))
        except (OSError, ValueError):
            continue
        times = (read(f"build/{name}/build.start.txt").strip()[11:19], read(f"build/{name}/build.end.txt").strip()[11:19])
        first = True
        for role in ("baseline", "good", "defective", "startcheck", "realstart"):
            if role not in doc:
                continue
            item = doc[role]
            rows.append(f"| {'`' + name + '` (' + times[0] + '-' + times[1] + 'Z)' if first else ''} | {role} | {item['version']} / {item['sequence']} | "
                        f"{item['commit']} | {item['tree']} | {item['sha256']} |")
            first = False
    return "\n".join(rows)


def part(name, start, end=None):
    text = read(name)
    if start not in text:
        return ""
    body = text.split(start, 1)[1]
    if end and end in body:
        body = body.split(end, 1)[0]
    return body.strip()


def cells_table():
    rows = ["| Run (folder) | Lab | Harness copy | Wrapper (UTC) | Overall | Steps or sections not passed |", "| --- | --- | --- | --- | --- | --- |"]
    for result in sorted(glob.glob(os.path.join(E, "**", "run-*"), recursive=True), key=lambda p: (read(os.path.relpath(os.path.join(p, "host", "wrapper.start.txt"), E)), p)):
        rel = os.path.relpath(result, E).replace("\\", "/")
        try:
            value = json.load(open(os.path.join(result, "result.json"), encoding="utf-8"))
        except (OSError, ValueError):
            value = {}
        lab = (read(rel + "/host/lab.txt").splitlines() or [""])[0].replace("lab=/var/tmp/cp-release-drill-", "")
        harness = re.search(r"harness-([a-z0-9]+)", read(rel + "/host/harness.txt"))
        bad = [f"{s['name']}: {s['verdict']}" for s in value.get("steps", []) if s.get("verdict") not in ("passed", "observed", "skipped")]
        rows.append(f"| {rel} | {lab} | {harness.group(1) if harness else '?'} | {read(rel + '/host/wrapper.start.txt').strip()[11:19]}-"
                    f"{read(rel + '/host/wrapper.end.txt').strip()[11:19]} | `{value.get('overall', 'no result')}` | {'; '.join(bad) or '-'} |")
    return "\n".join(rows)


def cdrive():
    lines = [l for l in (read("host/c-drive.txt") + read("host/c-drive-cells.txt")).splitlines() if "free_GiB=" in l]
    watch = [float(m.group(1)) for m in re.finditer(r"free_GiB=([0-9.]+)", read("host/c-drive-watch.txt"))]
    out = []
    for line in sorted(lines):
        m = re.match(r"(\S+) (.*?) (?:free_bytes=\d+ )?free_GiB=([0-9.]+)", line)
        if m:
            out.append(f"{m.group(3)} ({m.group(2).strip()}, {m.group(1)[11:16]}Z)")
    low = min(watch) if watch else None
    return "; ".join(out) + (f". Lowest of the {len(watch)} readings taken every 30 s by the watcher: **{low} GiB**; last: {watch[-1]} GiB." if watch else "")


text = "\n".join(open(name, encoding="utf-8").read().rstrip("\n") + "\n" for name in templates)
p2 = read("part2-table.md")
sections = ["## " + block for block in p2.split("\n## ")[1:]]


def facts(kind):
    chosen = [block.replace("## ", "#### ", 1).strip() for block in sections if kind in block.splitlines()[0]]
    return "\n\n".join(chosen)


values = {
    "BUILD_TABLE": build_table(),
    "PART1_TABLE": part("part1-table.md", "generated by tools/summary.py)\n", "\nRegression:"),
    "PART1_REGRESSION": part("part1-table.md", "latest run of each cell.\n"),
    "PART2_TABLE": p2.split("\n## ", 1)[0].split("generated by tools/summary.py)\n", 1)[-1].strip(),
    "PART2_FACTS_GOOD": facts("after the verified update"),
    "PART2_FACTS_BACK": facts("after the automatic return"),
    "CELLS_TABLE": cells_table(),
    "CDRIVE": cdrive(),
}
values.update(json.load(open(values_file, encoding="utf-8")))
for key, value in values.items():
    text = text.replace("{{" + key + "}}", value)
left = re.findall(r"\{\{[A-Z0-9_]+\}\}", text)
open(os.path.join(E, "README.md"), "w", encoding="utf-8", newline="\n").write(text)
print("README.md written;", "placeholders left: " + ", ".join(left) if left else "no placeholder left;", len(text.splitlines()), "lines")
