#!/usr/bin/env bash
set -euo pipefail
umask 077
PATH=/usr/bin:/bin
export PATH
readonly HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
fail() { printf 'rhel9-blocked-contract: FAIL: %s\n' "$*" >&2; exit 1; }
contains() { /usr/bin/grep -Fq -- "$2" "$1" || fail "$1 lacks: $2"; }
absent() { ! /usr/bin/grep -Fq -- "$2" "$1" || fail "$1 unexpectedly contains: $2"; }
ordered() {
 local file=$1 first=$2 second=$3 first_line second_line
 first_line=$(/usr/bin/grep -nF -- "$first" "$file" | /usr/bin/head -n 1 | /usr/bin/cut -d: -f1)
 second_line=$(/usr/bin/grep -nF -- "$second" "$file" | /usr/bin/head -n 1 | /usr/bin/cut -d: -f1)
 [[ "$first_line" =~ ^[0-9]+$ && "$second_line" =~ ^[0-9]+$ && "$first_line" -lt "$second_line" ]] ||
  fail "$file has unsafe source order: $first must precede $second"
}

for script in "$HERE/run.sh" "$HERE/remote-acceptance.sh"; do
 /bin/bash -n "$script" || fail "bash syntax: $script"
 contains "$script" 'set -euo pipefail'
done
contains "$HERE/run.sh" 'GlobalKnownHostsFile=/dev/null'
contains "$HERE/run.sh" 'export PATH LC_ALL LANG'
contains "$HERE/run.sh" 'UpdateHostKeys=no'
contains "$HERE/run.sh" 'VerifyHostKeyDNS=no'
contains "$HERE/run.sh" 'validate_local_file "$REMOTE"'
contains "$HERE/run.sh" 'transport=static-command'
contains "$HERE/run.sh" 'known_hosts must use a token-free absolute SSH path'
contains "$HERE/run.sh" 'identity file must use a token-free absolute SSH path'
contains "$HERE/run.sh" 'readonly CONTROLLER_EXPECTED_MACHINE_ID=%s\n'
contains "$HERE/run.sh" '/usr/bin/timeout --signal=TERM --kill-after=10s 300s /usr/bin/ssh'
contains "$HERE/run.sh" '/usr/bin/head -c 4097'
contains "$HERE/run.sh" 'remote output violates the closed result grammar'
contains "$HERE/run.sh" 'validate_remote_output "$inspection" inspect'
contains "$HERE/run.sh" 'validate_remote_output "$blocked" blocked'
absent "$HERE/run.sh" 'printf '\''%s\n'\'' "$inspection"'
absent "$HERE/run.sh" 'printf '\''%s\n'\'' "$blocked"'
absent "$HERE/run.sh" 'quote_remote'
absent "$HERE/remote-acceptance.sh" 'systemctl reboot'
absent "$HERE/remote-acceptance.sh" 'SKIP_DEPS'
absent "$HERE/remote-acceptance.sh" 'SKIP_ADMIN'
absent "$HERE/remote-acceptance.sh" 'CELIKPANEL_E2E_RHEL_DEFAULT_DENY=pass'
absent "$HERE/remote-acceptance.sh" 'CELIKPANEL_E2E_DNF_LOCK_RECOVERY=pass'
contains "$HERE/remote-acceptance.sh" 'RESULT durable-checkpoints=unchanged'
contains "$HERE/remote-acceptance.sh" '/usr/bin/env -i PATH='
contains "$HERE/run.sh" '/usr/bin/bash -s -- inspect almalinux'
contains "$HERE/remote-acceptance.sh" 'root_file "$t" 1'
contains "$HERE/remote-acceptance.sh" 'root_file /usr/sbin/iptables-save 1'
contains "$HERE/remote-acceptance.sh" '/usr/bin/bash "$INSTALLER"'
contains "$HERE/remote-acceptance.sh" 'PATH=/usr/sbin:/usr/bin:/sbin:/bin'
contains "$HERE/remote-acceptance.sh" 'readonly MOUNTINFO=/proc/$$/mountinfo'
contains "$HERE/remote-acceptance.sh" '/usr/bin/flock -n "$PROBE_LOCK_FD"'
contains "$HERE/remote-acceptance.sh" '[[ "$account_status" == 2 ]] || die "user account inventory failed"'
contains "$HERE/remote-acceptance.sh" '[[ "$account_status" == 2 ]] || die "group account inventory failed"'
contains "$HERE/remote-acceptance.sh" '/usr/bin/timeout --signal=TERM --kill-after=2s 10s /usr/bin/getent passwd celikpanel'
contains "$HERE/remote-acceptance.sh" '"$MACHINE" == "$CONTROLLER_EXPECTED_MACHINE_ID"'
contains "$HERE/remote-acceptance.sh" '"$MANIFEST_SUM" == "$CONTROLLER_EXPECTED_MANIFEST_SHA256"'
contains "$HERE/remote-acceptance.sh" '/usr/bin/find "$root" -xdev -print0 >"$raw" || return 1'
contains "$HERE/remote-acceptance.sh" 'LC_ALL=C /usr/bin/sort -z -- "$raw" >"$sorted" || return 1'
contains "$HERE/remote-acceptance.sh" 'state_hash after || post_state_rc=$?'
contains "$HERE/remote-acceptance.sh" '/usr/bin/timeout --signal=TERM --kill-after=10s 120s'
contains "$HERE/remote-acceptance.sh" '/etc/letsencrypt/renewal-hooks/deploy/celikpanel-panel-cert'
contains "$HERE/remote-acceptance.sh" '/usr/sbin/iptables-save >"$raw" || return 1'
contains "$HERE/remote-acceptance.sh" 's/^(# Generated by iptables-save .+ on) .+$/\1 TIME/'
contains "$HERE/remote-acceptance.sh" 's/^(# Completed on) .+$/\1 TIME/'
contains "$HERE/remote-acceptance.sh" '"$relative" =~ ^[A-Za-z0-9._/@+-]+$'
ordered "$HERE/remote-acceptance.sh" '"$relative" =~ ^[A-Za-z0-9._/@+-]+$' '[[ -n "${listed[$relative]+x}" ]]'
ordered "$HERE/remote-acceptance.sh" 'state_hash after || post_state_rc=$?' 'case "${pipe_status[0]}" in'
ordered "$HERE/remote-acceptance.sh" 'state_hash after || post_state_rc=$?' '/usr/bin/cmp -s -- "$clean" "$expected"'
absent "$HERE/remote-acceptance.sh" '/proc/self/mountinfo'
absent "$HERE/remote-acceptance.sh" 'done < <('
absent "$HERE/remote-acceptance.sh" 'PATH=/usr/local'
absent "$HERE/remote-acceptance.sh" '/usr/sbin/iptables-save -c'
absent "$HERE/remote-acceptance.sh" '${listed[${object#'
contains "$HERE/remote-acceptance.sh" '/var/lib/celikpanel-release-transaction'
contains "$HERE/remote-acceptance.sh" '/run/celikpanel-release-transaction'
contains "$HERE/remote-acceptance.sh" '/var/backups/celikpanel'
contains "$HERE/remote-acceptance.sh" '/var/lib/selinux'

[[ -n "${HOME:-}" && -d "$HOME" ]] || fail "secure HOME is required for contract fixtures"
tmp=$(mktemp -d "$HOME/.rhel9-blocked-contract.XXXXXX")
trap 'rm -rf -- "$tmp"' EXIT
chmod 700 "$tmp"
cp "$HERE/run.sh" "$HERE/remote-acceptance.sh" "$tmp/"
chmod 600 "$tmp/run.sh" "$tmp/remote-acceptance.sh"
controller=$tmp/run.sh

key_type=ssh-ed25519
base64_bin=/usr/bin/base64
[[ -x "$base64_bin" ]] || base64_bin=/usr/sbin/base64
openssl_bin=/usr/bin/openssl
[[ -x "$openssl_bin" ]] || openssl_bin=/usr/sbin/openssl
[[ -x "$base64_bin" && -x "$openssl_bin" ]] || fail 'base64 and openssl are required'
key_blob=$(
 {
  printf '\000\000\000\013ssh-ed25519\000\000\000\040'
  printf '0123456789abcdef0123456789abcdef'
 } | "$base64_bin"
)
key_blob=${key_blob//$'\n'/}
[[ "$key_blob" =~ ^AAAAC3NzaC1lZDI1NTE5AAAAI[A-Za-z0-9+/]{43}$ ]] || fail 'synthetic Ed25519 blob is invalid'
alias_name=celikpanel-alma9-contract
known_hosts=$tmp/known_hosts
printf '%s %s %s\n' "$alias_name" "$key_type" "$key_blob" > "$known_hosts"
chmod 600 "$known_hosts"
host_fingerprint=$(
 printf '%s' "$key_blob" |
  "$base64_bin" -d |
  "$openssl_bin" dgst -sha256 -binary |
  "$base64_bin"
)
host_fingerprint=${host_fingerprint//$'\n'/}
host_fingerprint=SHA256:${host_fingerprint//=}

hex64=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
hex32=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
nonce=cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
base=(
 CELIKPANEL_E2E_SSH_TARGET=root@alma9.example.invalid
 CELIKPANEL_E2E_EXPECT_ID=almalinux
 CELIKPANEL_E2E_KNOWN_HOSTS=$known_hosts
 CELIKPANEL_E2E_HOST_KEY_ALIAS=$alias_name
 CELIKPANEL_E2E_EXPECT_HOST_KEY_SHA256=$host_fingerprint
 CELIKPANEL_E2E_EXPECT_MANIFEST_SHA256=$hex64
 CELIKPANEL_E2E_EXPECT_MACHINE_ID=$hex32
 CELIKPANEL_E2E_EXPECT_TARGET_NONCE=$nonce
)
output=$(env "${base[@]}" /bin/bash "$controller") || fail "valid dry-run failed"
[[ "$output" == *'phases=inspect,blocked'* && "$output" == *'certification=not-implemented'* ]] ||
 fail "dry-run does not state its narrow scope"

reject() {
 local name=$1 value=$2 expected=$3 output status
 set +e
 output=$(env "${base[@]}" "$name=$value" /bin/bash "$controller" 2>&1)
 status=$?
 set -e
 [[ "$status" -ne 0 && "$output" == *"$expected"* ]] || fail "$name was not rejected safely"
}

bad_known_hosts=$tmp/bad-known-hosts
printf '%s  %s %s\n' "$alias_name" "$key_type" "$key_blob" > "$bad_known_hosts"
chmod 600 "$bad_known_hosts"
reject CELIKPANEL_E2E_KNOWN_HOSTS "$bad_known_hosts" 'must pin only the exact alias'
printf '%s,%s %s %s\n' "$alias_name" other-alias "$key_type" "$key_blob" > "$bad_known_hosts"
reject CELIKPANEL_E2E_KNOWN_HOSTS "$bad_known_hosts" 'must pin only the exact alias'

payload="x' </tmp/evil #"
legacy=(
 CELIKPANEL_E2E_REMOTE_INSTALLER
 CELIKPANEL_E2E_REMOTE_RELEASE_ROOT
 CELIKPANEL_E2E_REMOTE_INSTALL_HOOK
 CELIKPANEL_E2E_REMOTE_UPDATE_HOOK
 CELIKPANEL_E2E_REMOTE_ROLLBACK_HOOK
 CELIKPANEL_E2E_REMOTE_DNF_LOCK_HOOK
 CELIKPANEL_E2E_REMOTE_DEFAULT_DENY_HOOK
 CELIKPANEL_E2E_EXPECT_AGENT_SELINUX_TYPE
 CELIKPANEL_E2E_EXPECT_PANEL_SELINUX_TYPE
 CELIKPANEL_E2E_CERTIFY_RHEL9
 CELIKPANEL_E2E_ALLOW_REBOOT
)
for name in "${legacy[@]}"; do
 reject "$name" "$payload" 'unsupported and must be unset'
done
reject CELIKPANEL_E2E_MODE certify 'only blocked mode exists'
reject CELIKPANEL_E2E_DRY_RUN 0 'requires the exact target nonce as explicit approval'
reject CELIKPANEL_E2E_EXPECT_ID "alma' > /tmp/evil" 'expected distro'
reject CELIKPANEL_E2E_EXPECT_ID $'almalinux\nrocky' 'expected distro'
reject CELIKPANEL_E2E_HOST_KEY_ALIAS "host' </tmp/evil" 'host-key alias'
reject CELIKPANEL_E2E_EXPECT_MANIFEST_SHA256 "$hex64>" 'manifest digest'
reject CELIKPANEL_E2E_EXPECT_MACHINE_ID "$hex32'" 'machine ID'
reject CELIKPANEL_E2E_EXPECT_TARGET_NONCE "${nonce}"$'\n' 'target nonce'
reject CELIKPANEL_E2E_SSH_PORT '22>file' 'SSH port'
reject CELIKPANEL_E2E_EXPECT_HOST_KEY_SHA256 SHA256:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 'host-key fingerprint mismatch'

unsafe_known_hosts="$tmp/known hosts"
cp "$known_hosts" "$unsafe_known_hosts"
chmod 600 "$unsafe_known_hosts"
reject CELIKPANEL_E2E_KNOWN_HOSTS "$unsafe_known_hosts" 'token-free absolute SSH path'
unsafe_known_token="$tmp/known%h"
cp "$known_hosts" "$unsafe_known_token"
chmod 600 "$unsafe_known_token"
reject CELIKPANEL_E2E_KNOWN_HOSTS "$unsafe_known_token" 'token-free absolute SSH path'
unsafe_identity="$tmp/identity%h"
cp "$controller" "$unsafe_identity"
chmod 600 "$unsafe_identity"
reject CELIKPANEL_E2E_IDENTITY_FILE "$unsafe_identity" 'token-free absolute SSH path'

set +e
output=$(env "${base[@]}" CELIKPANEL_E2E_DRY_RUN=0 CELIKPANEL_E2E_ALLOW_REMOTE_BLOCKED_NONCE=dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd /bin/bash "$controller" 2>&1)
status=$?
set -e
[[ "$status" -ne 0 && "$output" == *'requires the exact target nonce as explicit approval'* ]] ||
 fail 'wrong remote nonce approval was not rejected'

printf 'rhel9-blocked-contract: PASS\n'
