package transport

import (
	"fmt"
	"strings"
)

const (
	MinMailboxPasswordBytes = 8
	MaxMailboxPasswordBytes = 1024
	MaxMailboxQuotaMB       = 1_048_576
)

// MailAccount and MailForwarding are the full-state mail configuration records
// exchanged by panel and agent. Password is request-scoped and must never be
// logged or persisted outside the account creation flow.
type MailAccount struct {
	Email    string `json:"email"`
	Password string `json:"password,omitempty"`
	QuotaMB  int    `json:"quota_mb"`
}

type MailForwarding struct {
	Source      string `json:"source"`
	Destination string `json:"destination"`
}

type MailConfigSyncRequest struct {
	Accounts    []MailAccount    `json:"accounts"`
	Forwardings []MailForwarding `json:"forwardings"`
	Domains     []string         `json:"domains"`
}

type DeleteMailAccountRequest struct {
	Email string `json:"email"`
}

// UpdateMailPasswordRequest carries a password only for the lifetime of one
// privileged panel-to-agent mutation. Callers must never log or persist the
// NewPassword field.
type UpdateMailPasswordRequest struct {
	ExpectedBuildCommit string `json:"expected_build_commit"`
	Email               string `json:"email"`
	NewPassword         string `json:"new_password"`
}

// DeleteMailDomainRequest identifies one immutable domain deletion. The
// privileged agent independently validates the canonical domain and binds the
// filesystem mutation to the exact panel build that authorized it.
type DeleteMailDomainRequest struct {
	ExpectedBuildCommit string `json:"expected_build_commit"`
	DomainID            int    `json:"domain_id"`
	Domain              string `json:"domain"`
}

// DeleteMailDomainResponse confirms convergence, not merely that this call
// changed bytes. Applied is therefore true on a safe idempotent retry too.
// Quarantined reports whether a current or previous call preserved a Maildir.
type DeleteMailDomainResponse struct {
	Applied     bool `json:"applied"`
	Quarantined bool `json:"quarantined"`
}

type UpdateMailForwardingRequest struct {
	Forwardings []MailForwarding `json:"forwardings"`
}

type ImportMailAccountRequest struct {
	Email     string `json:"email"`
	CryptHash string `json:"crypt_hash"`
	QuotaMB   int    `json:"quota_mb"`
}

type UpdateMailQuotaRequest struct {
	Email   string `json:"email"`
	QuotaMB int    `json:"quota_mb"`
}

// MailMutationResponse is deliberately not a bare bool. The panel must not
// report success unless the agent explicitly confirms that the complete
// mutation was published.
type MailMutationResponse struct {
	Applied bool `json:"applied"`
}

// ValidateMailboxPassword enforces the shared panel/agent wire boundary. The
// length is measured in bytes because that is what doveadm receives. Line
// protocol delimiters are rejected before the password is written to stdin.
func ValidateMailboxPassword(password string) error {
	if len(password) < MinMailboxPasswordBytes || len(password) > MaxMailboxPasswordBytes {
		return fmt.Errorf("mailbox password must be between %d and %d bytes", MinMailboxPasswordBytes, MaxMailboxPasswordBytes)
	}
	if strings.ContainsAny(password, "\r\n\x00") {
		return fmt.Errorf("mailbox password contains an unsupported control character")
	}
	return nil
}

// CanonicalMailAddress accepts the deliberately conservative address syntax
// supported by CelikPanel's Postfix/Dovecot map files. Display names, quoted
// local parts, comments, whitespace and multiple recipients are not accepted.
func CanonicalMailAddress(raw string) (string, error) {
	raw = strings.TrimSpace(raw)
	if len(raw) == 0 || len(raw) > 254 || strings.Count(raw, "@") != 1 {
		return "", fmt.Errorf("email address must contain exactly one @")
	}
	parts := strings.SplitN(raw, "@", 2)
	local := parts[0]
	domain := strings.ToLower(parts[1])
	if !validMailLocalPart(local) {
		return "", fmt.Errorf("invalid email local part")
	}
	if !validMailDomain(domain) {
		return "", fmt.Errorf("invalid email domain")
	}
	return strings.ToLower(local) + "@" + domain, nil
}

// CanonicalMailboxForDomain accepts a local part or full address, but the
// resulting mailbox must belong to expectedDomain.
func CanonicalMailboxForDomain(raw, expectedDomain string) (string, error) {
	expectedDomain = strings.ToLower(strings.TrimSpace(expectedDomain))
	if !validMailDomain(expectedDomain) {
		return "", fmt.Errorf("invalid managed domain")
	}
	raw = strings.TrimSpace(raw)
	if !strings.Contains(raw, "@") {
		raw += "@" + expectedDomain
	}
	address, err := CanonicalMailAddress(raw)
	if err != nil {
		return "", err
	}
	if !strings.HasSuffix(address, "@"+expectedDomain) {
		return "", fmt.Errorf("mailbox must belong to %s", expectedDomain)
	}
	return address, nil
}

// CanonicalForwardSource validates either a mailbox or Postfix's @domain
// catch-all key. Catch-all keys are generated by the panel, never accepted
// directly from the domain forwarding endpoint.
func CanonicalForwardSource(raw string) (string, error) {
	raw = strings.TrimSpace(raw)
	if strings.HasPrefix(raw, "@") {
		domain := strings.ToLower(strings.TrimPrefix(raw, "@"))
		if !validMailDomain(domain) {
			return "", fmt.Errorf("invalid catch-all domain")
		}
		return "@" + domain, nil
	}
	return CanonicalMailAddress(raw)
}

func validMailLocalPart(local string) bool {
	if len(local) == 0 || len(local) > 64 || local[0] == '.' || local[len(local)-1] == '.' || strings.Contains(local, "..") {
		return false
	}
	for _, r := range local {
		alnum := r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9'
		if !alnum && r != '.' && r != '_' && r != '-' && r != '+' {
			return false
		}
	}
	return true
}

func validMailDomain(domain string) bool {
	if len(domain) == 0 || len(domain) > 253 || strings.HasPrefix(domain, ".") || strings.HasSuffix(domain, ".") {
		return false
	}
	for _, label := range strings.Split(domain, ".") {
		if len(label) == 0 || len(label) > 63 || label[0] == '-' || label[len(label)-1] == '-' {
			return false
		}
		for _, r := range label {
			if !(r >= 'a' && r <= 'z' || r >= '0' && r <= '9' || r == '-') {
				return false
			}
		}
	}
	return true
}

type MailQuotaUsage struct {
	Email     string `json:"email"`
	UsedKB    int64  `json:"used_kb"`
	LimitKB   int64  `json:"limit_kb"`
	Available bool   `json:"available"`
}

type MailQuotaStatusRequest struct {
	Emails []string `json:"emails"`
}

type MailQuotaStatusResponse struct {
	PluginEnabled bool             `json:"plugin_enabled"`
	Usages        []MailQuotaUsage `json:"usages"`
}

type MailSNIEntry struct {
	Names    []string `json:"names"`
	CertPath string   `json:"cert_path"`
	KeyPath  string   `json:"key_path"`
}

// DefaultMailTLSCertificatePath is the fixed agent-owned fallback certificate
// published when no trusted per-domain mail certificate is available.
const DefaultMailTLSCertificatePath = "/etc/ssl/celikpanel/_mail/default-cert.pem"

type SecureMailTLSRequest struct {
	ExpectedBuildCommit string         `json:"expected_build_commit"`
	Myhostname          string         `json:"myhostname"`
	SNI                 []MailSNIEntry `json:"sni"`
}

// ReconcileMailTLSMutationRequest binds the mail TLS reconciliation to the
// durable service mutation that authorized it. SecureMailTLSRequest remains
// the legacy lifecycle contract; new multi-service orchestration must use this
// request so the privileged agent can prove lease ownership for the whole
// step.
type ReconcileMailTLSMutationRequest struct {
	ServiceMutationBinding
	ExpectedBuildCommit string         `json:"expected_build_commit"`
	Myhostname          string         `json:"myhostname"`
	SNI                 []MailSNIEntry `json:"sni"`
}

// SyncMailTLSV2Request carries the complete canonical mail TLS snapshot under
// a fresh direct payload-bound mutation. Package/profile operations must
// terminalize before opening this independent lease.
type SyncMailTLSV2Request struct {
	ServiceMutationBinding
	ExpectedBuildCommit string         `json:"expected_build_commit"`
	Myhostname          string         `json:"myhostname"`
	SNI                 []MailSNIEntry `json:"sni"`
}

type SecureMailTLSResponse struct {
	Configured  bool   `json:"configured"`
	DefaultCert string `json:"default_cert"`
	SNICount    int    `json:"sni_count"`
	Detail      string `json:"detail,omitempty"`
	Error       string `json:"error,omitempty"`
}
