"""set2: tables and extracts generated from the staged evidence (read-only over the cells' JSON files).

usage: summary.py EVIDENCE_DIR  -> sections-table.md, checks-not-passed.txt, texts-en-tr.md, group-b-service-actions.md,
       group-c-request-identity.md, native-facts.json in EVIDENCE_DIR
"""
import glob
import json
import os
import sys

E = sys.argv[1]
STANDARD = {"section", "title", "node", "native_evidence", "started_at", "finished_at", "calls", "checks", "natives", "notes",
            "owner_actions", "verdict", "substeps"}


def load(path):
    with open(path, encoding="utf-8") as stream:
        return json.load(stream)


def runs():
    found = []
    for result in sorted(glob.glob(os.path.join(E, "*", "run-*", "result.json"))):
        directory = os.path.dirname(result)
        found.append((os.path.relpath(directory, E).replace("\\", "/"), directory, load(result)))
    return found


def sections(directory):
    out = []
    for path in sorted(glob.glob(os.path.join(directory, "steps", "*", "section.json"))):
        out.append((os.path.basename(os.path.dirname(path)), load(path)))
    return out


def seconds(a, b):
    import datetime as dt
    try:
        f = "%Y-%m-%dT%H:%M:%SZ"
        return int((dt.datetime.strptime(b, f) - dt.datetime.strptime(a, f)).total_seconds())
    except (TypeError, ValueError):
        return None


def one_line(value, limit=400):
    text = json.dumps(value, ensure_ascii=False, sort_keys=True)
    return text if len(text) <= limit else text[:limit] + " ..."


# -- sections-table.md and checks-not-passed.txt ---------------------------------------------------------------------
table, notpassed = ["# set2: steps and sections per run (generated by tools/summary.py)", ""], []
for name, directory, result in runs():
    table += [f"### {name}: overall `{result['overall']}`, node {result['identity']['node']}, cell kind `{result['cell_kind']}`, "
              f"`native_evidence: {str(result['native_evidence']).lower()}`", "",
              "| Step | Verdict | Started (UTC) | Finished (UTC) | Seconds |", "| --- | --- | --- | --- | --- |"]
    for step in result["steps"]:
        table.append(f"| {step['name']} | {step['verdict']} | {step.get('started_at')} | {step.get('finished_at')} | "
                     f"{seconds(step.get('started_at'), step.get('finished_at'))} |")
    table += ["", "| Section | Verdict | Sub-steps | Checks | Not passed |", "| --- | --- | --- | --- | --- |"]
    for _, section in sections(directory):
        checks = section["checks"]
        bad = [c for c in checks if c["ok"] is not True]
        subs = ", ".join(f"{k} {v}" for k, v in (section.get("substeps") or {}).items())
        table.append(f"| {section['section']} | **{section['verdict']}** | {subs[:700]} | {len(checks)} | {len(bad) or '-'} |")
        if section.get("error"):
            notpassed.append(f"{name} {section['section']} ERROR: {section['error'][:1500]}")
        for check in bad:
            notpassed.append(f"{name} {section['section']} {'FAIL' if check['ok'] is False else 'NOT ESTABLISHED'}: {check['name']}")
            notpassed.append("    " + one_line(check["detail"], 1800))
        for note in section.get("notes", []):
            notpassed.append(f"{name} {section['section']} note: {note['note']}")
            notpassed.append("    " + one_line(note.get("detail"), 900))
    table.append("")
open(os.path.join(E, "sections-table.md"), "w", encoding="utf-8", newline="\n").write("\n".join(table) + "\n")
open(os.path.join(E, "checks-not-passed.txt"), "w", encoding="utf-8", newline="\n").write("\n".join(notpassed) + "\n")

# -- texts-en-tr.md -----------------------------------------------------------------------------------------------------
texts = ["# set2: verbatim answers (generated by tools/summary.py)", "",
         "Each distinct refusal or failure answer with its status, code, reason, the API's own English sentence, the values it",
         "carried, and the catalogue sentences of the installed build looked up by key (EN and TR). The driver renders no",
         "screen. `seen in` names the runs and the first request label.", "",
         "H37: for `CONFIG_RELOAD_FAILED`, `CURRENT_SETTINGS_UNREADABLE` / `scheduled_tasks`, `MAIL_QUEUE_UNREADABLE` and",
         "`MAIL_POLICY_NOT_RELOADED` the driver's own key list was older than the screens; the sentences below are the",
         "ones the screens of this build use for that answer (`ConfigFileNotices`, `DomainCronManager`, the queue tab, the",
         "mail policy card), looked up here in the same catalogue. The `catalogue_texts` inside the cells' `section.json`",
         "files keep what the driver attached.", ""]
# H37: for the answers below the driver's own list of screen keys was older than the screens (it attached
# `dbconf.reloadFailed.notRestored`, `cron.unknown`, `postfix.queue.unknown` and the stage-less mail policy sentence).
# The keys the screens of this build use (web/src/components at the candidate commit) are looked up here in the same
# catalogue, with the answer's own values.
REPO = os.path.abspath(os.path.join(E, "..", "..", "..", "..", ".."))
sys.path.insert(0, os.path.join(REPO, "deploy", "e2e", "dns-pair-acceptance"))
try:
    import guidance
    from pathlib import Path
    CATALOG = guidance.load_catalog(Path(REPO) / "web" / "src" / "i18n")
except Exception as exc:  # noqa: BLE001
    CATALOG = None
    print("catalogue not loaded:", exc)


def screen_keys(code, reason, detail):
    if code == "CONFIG_RELOAD_FAILED":
        return ["dbconf.reloadFailed." + (reason if reason in ("restored", "restored_unit_reload_failed", "restored_running_unknown") else "notRestored"),
                "dbconf.reloadSaid"]
    if code == "CURRENT_SETTINGS_UNREADABLE" and reason == "scheduled_tasks":
        return (["cron.unknown." + detail] if detail else ["cron.unknown"]) + ["cron.unknown.said"]
    if code == "MAIL_QUEUE_UNREADABLE":
        return ["postfix.queue.unreadable" + ("." + reason if reason else ""), "postfix.queue.said"]
    if code == "MAIL_POLICY_NOT_RELOADED":
        return ["err.MAIL_POLICY_NOT_RELOADED" + ("." + reason if reason else ""), "mailpolicy.postfixSaid"]
    return None


def corrected(answer, texts, values):
    detail = answer.get("detail")
    if not detail and answer.get("code") == "CURRENT_SETTINGS_UNREADABLE" and "/etc/cron.allow" in str(answer.get("error")):
        detail = "cron_allow"     # the settings driver did not keep the answer's `detail` token; its sentence names the cause
    keys = screen_keys(answer.get("code"), answer.get("reason"), detail)
    if not keys or CATALOG is None:
        return texts
    out = {}
    for key in keys:
        if key in CATALOG["en"]:
            out[key] = {}
            for language in ("en", "tr"):
                text = CATALOG[language].get(key, key)
                for name, value in values.items():
                    text = text.replace("{" + name + "}", str(value))
                out[key][language] = text
    return out


seen = {}
for name, directory, result in runs():
    for _, section in sections(directory):
        for call in section["calls"]:
            answer = call.get("answer")
            if not answer or not (answer.get("code") or answer.get("error")):
                continue
            key = (call.get("status"), answer.get("code"), answer.get("reason"), answer.get("error"))
            entry = seen.setdefault(key, {"where": [], "vars": [], "texts": {}, "detail": set()})
            if len(entry["where"]) < 6:
                entry["where"].append(f"{name} {section['section']}: {call['label']}")
            if answer.get("vars") and len(entry["vars"]) < 3 and answer["vars"] not in entry["vars"]:
                entry["vars"].append(answer["vars"])
            if answer.get("detail"):
                entry["detail"].add(str(answer["detail"]))
            values = dict(answer.get("vars") or {})
            values.setdefault("service", "PostgreSQL" if "postgresql" in str(values.get("unit", "")) else values.get("unit", ""))
            for k, v in corrected(answer, call.get("catalogue_texts") or {}, values).items():
                entry["texts"].setdefault(k, v)
for (status, code, reason, error), entry in sorted(seen.items(), key=lambda item: (str(item[0][1]), str(item[0][2]), str(item[0][0]))):
    texts.append(f"## `{status} {code or '(no code)'}`" + (f" / `{reason}`" if reason else ""))
    texts.append("")
    texts.append(f"- API: \"{error}\"")
    if entry["detail"]:
        texts.append(f"- `detail` (cause token): {', '.join(sorted(entry['detail']))}")
    for item in entry["vars"]:
        texts.append(f"- vars: `{one_line(item, 700)}`")
    for key, value in entry["texts"].items():
        texts.append(f"- `{key}`")
        texts.append(f"  - EN: \"{value.get('en')}\"")
        texts.append(f"  - TR: \"{value.get('tr')}\"")
    texts.append(f"- seen in: {'; '.join(entry['where'])}")
    texts.append("")
open(os.path.join(E, "texts-en-tr.md"), "w", encoding="utf-8", newline="\n").write("\n".join(texts) + "\n")

# -- group B --------------------------------------------------------------------------------------------------------------
lines = ["# set2 group B: service actions through `POST /api/v1/service/action` (generated by tools/summary.py)", "",
         "`said`: what the answer says (success, failed, unknown). `truth`: whether the action took effect, read natively",
         "(start: the daemon runs; stop: it does not; restart: it runs with a new process; reload: it runs with the same",
         "process, a reload is visible and the unit reports no failed reload). `match`: said == truth.", ""]
facts = {}
for name, directory, result in runs():
    for step, section in sections(directory):
        if not section["section"].startswith("S8"):
            continue
        lines += [f"## {name} ({section['started_at']} - {section['finished_at']}, verdict {section['verdict']})", "",
                  "| Service | Action | Situation | At (UTC) | Answer | reason | unit / applied | said | truth | match | Daemon PID before -> after | Reload evidence |",
                  "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
        for a in section.get("actions", []):
            answer = a.get("answer") or {}
            vars_ = a.get("vars") or {}
            match = {True: "yes", False: "**NO**", None: "n/a (unknown)"}[a["matches"]]
            lines.append(f"| {a['service']} | {a['action']} | {a['situation'] or 'healthy'} | {a['at'][11:19]} | {a['status']} {a['code'] or ''} | "
                         f"{a['reason'] or ''} | {vars_.get('owner_unit') or answer.get('unit') or ''} {answer.get('applied') or ''} | {a['said']} | "
                         f"{'took effect' if a['truth_action_took_effect'] else 'no effect'} | {match} | "
                         f"{a['daemon_before']['pid']} ({'up' if a['daemon_before']['running'] else 'down'}) -> "
                         f"{a['daemon_after']['pid']} ({'up' if a['daemon_after']['running'] else 'down'}) | {'; '.join(a['reload_evidence']) or '-'} |")
        lines.append("")
        lines.append("Details of the answers that are not a plain success:")
        lines.append("")
        for a in section.get("actions", []):
            if a["said"] != "success":
                lines.append(f"- {a['service']} {a['action']} ({a['situation'] or 'healthy'}): `{a['status']} {a['code']}/{a['reason']}` vars "
                             f"`{one_line(a.get('vars'), 600)}`; units after: `{one_line(a['daemon_after']['units'], 500)}`")
        lines.append("")
        facts[name] = {"unit_facts": section.get("unit_facts"), "reload_hook": section.get("reload_hook")}
open(os.path.join(E, "group-b-service-actions.md"), "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")

# -- group C --------------------------------------------------------------------------------------------------------------
lines = ["# set2 group C: request identity, route x arrival (generated by tools/summary.py)", "",
         "i: the same request three times in a row. ii: three times at once. iii: without the header. iv: the same identity,",
         "a different body. v: the connection dropped mid-flight. vi: the Panel restarted mid-restore. vii: the rows.",
         "`-`: not part of this route's plan.", ""]
for name, directory, result in runs():
    if result["cell_kind"] != "request-identity":
        continue
    lines += [f"## {name} (overall `{result['overall']}`)", "", "| Route | i | ii | iii | iv | v | vi | vii | Times (UTC) |",
              "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    order = ["domain-database-mariadb", "domain-database-postgresql", "admin-account-mariadb", "admin-account-postgresql",
             "server-database-mariadb", "server-database-postgresql", "backup", "restore", "letsencrypt", "vpn-peer", "import", "rows"]
    section_times = {s["section"]: s for _, s in sections(directory)}
    for route in order:
        cells = result["matrix"].get(route, {})
        times = result.get("times", {}).get(route, {})
        if route == "restore" and "C8-restore" in section_times:
            times = {"started_at": section_times["C8-restore"]["started_at"], "finished_at": section_times["C8-restore"]["finished_at"]}
        if route == "rows" and "C9-identities" in section_times:
            times = {"started_at": section_times["C9-identities"]["started_at"], "finished_at": section_times["C9-identities"]["finished_at"]}
        label = result["routes"].get(route, "request_identities rows")
        lines.append(f"| {label} | " + " | ".join(cells.get(r, "-") for r in ("i", "ii", "iii", "iv", "v", "vi", "vii"))
                     + f" | {times.get('started_at', '')[11:19]}-{times.get('finished_at', '')[11:19]} |")
    lines.append("")
    for step, section in sections(directory):
        lines.append(f"- {section['section']}: {section['verdict']} ({section['started_at'][11:19]}-{section['finished_at'][11:19]}, "
                     f"{len(section['checks'])} checks, {sum(1 for c in section['checks'] if c['ok'] is not True)} not passed)")
        extra = {k: v for k, v in section.items() if k not in STANDARD and k not in ("fixtures", "rows", "panel_restart")}
        facts.setdefault(name, {})[section["section"]] = {k: v for k, v in section.items() if k not in STANDARD}
    lines.append("")
open(os.path.join(E, "group-c-request-identity.md"), "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")

# -- native-facts.json ------------------------------------------------------------------------------------------------------
for name, directory, result in runs():
    if result["cell_kind"] != "settings-writes":
        continue
    entry = facts.setdefault(name, {})
    entry["setup"] = result.get("setup")
    entry["site"] = result.get("site")
    for step, section in sections(directory):
        entry[section["section"]] = {k: v for k, v in section.items() if k not in STANDARD and k not in ("actions", "unit_facts")}
open(os.path.join(E, "native-facts.json"), "w", encoding="utf-8", newline="\n").write(json.dumps(facts, indent=1, sort_keys=True, ensure_ascii=False) + "\n")
print("written:", ", ".join(sorted(f for f in os.listdir(E) if os.path.isfile(os.path.join(E, f)))))

# -- group A ------------------------------------------------------------------------------------------------------------------
GROUPS = (
    ("A1 mail policy: healthy save reloads (S2 c)", "S2-mail-policy", ("c:",)),
    ("A1 mail policy: refused main.cf -> 502 check with policy (S2 f)", "S2-mail-policy", ("f:",)),
    ("A1 mail policy: unchanged save reloads (S2 g)", "S2-mail-policy", ("g:",)),
    ("A1 mail policy: stopped Postfix stays stopped (S2 h)", "S2-mail-policy", ("h:",)),
    ("A2 PostgreSQL reload hook -> restored_unit_reload_failed (S4 g)", "S4-postgresql", ("g:",)),
    ("A3 O1 MariaDB `plenty` refused; stock file saves (S5 b, c)", "S5-mariadb", ("b:", "c (adjusted value)")),
    ("A3 O3 cron.allow cause; relocated spool neutral (S1 f)", "S1-cron", ("f (", "f:")),
    ("A3 O3 queue: main.cf typo -> postfix_config (S6)", "S6-catchall-queue", ("queue (owner's typo)",)),
    ("A3 O5 each configuration file listed once (S7)", "S7-file-metadata", ("O5",)),
)
lines = ["# set2 group A: the set1 corrections re-measured (generated by tools/summary.py)", ""]
names = [n for n, _, r in runs() if r["cell_kind"] == "settings-writes"]
lines += ["| Item | " + " | ".join(names) + " |", "| --- |" + " --- |" * len(names)]
per_run = {}
for name, directory, result in runs():
    if result["cell_kind"] != "settings-writes":
        continue
    per_run[name] = {s["section"]: s for _, s in sections(directory)}
    per_run[name]["_dir"] = directory
for title, section_id, prefixes in GROUPS:
    row = []
    for name in names:
        section = per_run[name].get(section_id)
        if not section:
            row.append("not run")
            continue
        mine = [c for c in section["checks"] if c["name"].startswith(prefixes)]
        if not mine:
            row.append("not reached" + (" (section error)" if section.get("error") else ""))
        elif any(c["ok"] is False for c in mine):
            row.append(f"**FAIL** ({sum(1 for c in mine if c['ok'] is False)} of {len(mine)} checks)")
        elif any(c["ok"] is None for c in mine):
            row.append(f"not established ({sum(1 for c in mine if c['ok'] is None)} of {len(mine)})")
        else:
            row.append(f"pass ({len(mine)} checks)")
    lines.append(f"| {title} | " + " | ".join(row) + " |")
row = []
for name in names:
    try:
        step = load(os.path.join(per_run[name]["_dir"], "steps", "06-setup", "step.json"))
        wait = step["checks"].get("isolated_host_wait") or {}
        done = [k for k, v in (wait.get("steps") or {}).items() if v == "succeeded"]
        bad = [k + "=" + v for k, v in (wait.get("steps") or {}).items() if v in ("failed", "error")]
        row.append(("pass" if wait.get("phase") == "access_dns" and not bad and len(done) >= 9 else "**FAIL**")
                   + f": step {step['verdict']}, waits at `{wait.get('phase')}` ({wait.get('code')}); {len(done)} steps succeeded"
                   + (f"; failed {bad}" if bad else "") + f"; mail steps reached: {wait.get('mail_steps_reached')}")
    except (OSError, KeyError) as exc:
        row.append("no setup record: " + type(exc).__name__)
lines.append("| A4 setup completes to the isolated DNS wait | " + " | ".join(row) + " |")
lines += ["", "Regression (every section that passed in set1):", "", "| Section | " + " | ".join(names) + " |", "| --- |" + " --- |" * len(names)]
for section_id in ("S1-cron", "S2-mail-policy", "S3-backup-schedule", "S4-postgresql", "S5-mariadb", "S6-catchall-queue", "S7-file-metadata", "S8-service-actions"):
    row = []
    for name in names:
        section = per_run[name].get(section_id)
        if not section:
            row.append("not run")
            continue
        bad = [c for c in section["checks"] if c["ok"] is not True]
        row.append(f"**{section['verdict']}** ({len(section['checks'])} checks, {len(bad)} not passed; {section['started_at'][11:19]}-{section['finished_at'][11:19]})")
    lines.append(f"| {section_id} | " + " | ".join(row) + " |")
open(os.path.join(E, "group-a-settings-writes.md"), "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
print("group A table written")
