"""Offline tests of set8's pure rules: where the owner's lines go in a vhost, the index edit, and how a run's file is
classified. No guest is needed."""
from __future__ import annotations

import importlib.util
from pathlib import Path
import sys
import unittest

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))
import set8_trial as s8  # noqa: E402


def guest_module():
    spec = importlib.util.spec_from_file_location("set8_guest_under_test", HERE / "guest_set8_native.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


VHOST = """# Nginx vhost for set8-a.test
# Generated by CelikPanel — do not edit by hand / elle düzenlemeyin
# Site ID: 3 · Project type: php
# Validation-only names such as mail.<domain>. {not a brace}
server {
    listen 80;
    server_name mail.set8-a.test;
    location / {
        return 404;
    }
}
server {
    listen 80;
    server_name set8-a.test www.set8-a.test;
    root /var/www/x;
    index index.php index.html index.htm;
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
}
"""


class Set8Rules(unittest.TestCase):
    def setUp(self):
        self.g = guest_module()

    def test_block_end_is_the_main_server_block_not_the_acme_one(self):
        end = self.g.server_block_end(VHOST, "set8-a.test")
        self.assertEqual(VHOST.split("\n")[end], "}")
        self.assertGreater(end, VHOST.split("\n").index("    server_name set8-a.test www.set8-a.test;"))

    def test_no_block_for_another_name(self):
        self.assertIsNone(self.g.server_block_end(VHOST, "other.test"))
        with self.assertRaises(self.g.Refused):
            self.g.insert_before_block_end(VHOST, "other.test", ["x"])

    def test_lines_go_inside_the_block(self):
        text = self.g.insert_before_block_end(VHOST, "set8-a.test", ["    location /owner-extra/ {", "    }"])
        lines = text.split("\n")
        self.assertEqual(lines[-3:], ["    }", "}", ""])
        self.assertIn("    location /owner-extra/ {", lines)
        self.assertEqual(self.g.server_block_end(text, "set8-a.test"), len(lines) - 2)

    def test_index_edit(self):
        text, old, new = self.g.change_index(VHOST)
        self.assertEqual(old, "index index.php index.html index.htm;")
        self.assertEqual(new, "index set8-owner-index.html index.php index.html index.htm;")
        self.assertIn(new, text)
        with self.assertRaises(self.g.Refused):
            self.g.change_index(text)

    def test_file_class(self):
        self.assertEqual(s8.file_class({"exists": False}, "p", "e"), "absent")
        self.assertEqual(s8.file_class({"exists": True, "sha256": "e"}, "p", "e"), "owner-bytes-kept")
        self.assertEqual(s8.file_class({"exists": True, "sha256": "p"}, "p", "e"), "panel-text-written")
        self.assertEqual(s8.file_class({"exists": True, "sha256": "x"}, "p", "e"), "other-bytes")
        self.assertEqual(s8.file_class({"exists": True, "sha256": "r"}, {"p", "r"}, "e"), "panel-text-written")

    def test_provisional_verdict(self):
        self.assertEqual(s8.provisional_verdict("panel-text-written", True, True, False), "overwritten silently")
        self.assertEqual(s8.provisional_verdict("owner-bytes-kept", True, True, False), "kept silently")
        self.assertEqual(s8.provisional_verdict("owner-bytes-kept", True, False, False), "refused")
        self.assertEqual(s8.provisional_verdict("panel-text-written", False, None, False), "Panel failed to start")
        self.assertEqual(s8.provisional_verdict("other-bytes", True, True, True), "unknown")

    def test_runs_cover_every_vhost_scenario(self):
        self.assertEqual({r[1] for r in s8.RUNS}, set("abcde"))
        self.assertEqual({r[2] for r in s8.RUNS}, set(s8.OWNER_PATHS))


if __name__ == "__main__":
    unittest.main()
